name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Debug container and network status
        run: |
          docker-compose -f docker-compose.ci.yml ps
          docker-compose -f docker-compose.ci.yml logs app
          docker-compose -f docker-compose.ci.yml logs db
          docker network ls
          docker network inspect flask-docker-devops_default || true
      - name: Build and test Docker image
        run: |
          docker-compose -f docker-compose.ci.yml up -d
          # Wait for the app to be ready
          for i in {1..30}; do
            if curl --output /dev/null --silent --head --fail http://localhost:5000; then
              echo "App is up!"
              break
            else
              echo "Waiting for app..."
              sleep 2
            fi
          done
          # Test the app
          curl --retry 5 --retry-delay 5 http://localhost:5000 || exit 1
          docker-compose -f docker-compose.ci.yml down
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: farvezanzam/flask-app:latest
